"""Create tables Users and Actions

Revision ID: 28be2e2e67a5
Revises: 
Create Date: 2024-06-23 03:10:21.631657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28be2e2e67a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fullname', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_Users_telegram_id'), 'Users', ['telegram_id'], unique=True)
    op.create_table('Actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Actions_id'), 'Actions', ['id'], unique=True)
    op.create_index(op.f('ix_Actions_message'), 'Actions', ['message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Actions_message'), table_name='Actions')
    op.drop_index(op.f('ix_Actions_id'), table_name='Actions')
    op.drop_table('Actions')
    op.drop_index(op.f('ix_Users_telegram_id'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
