"""Create table Actions

Revision ID: 99099f0055cf
Revises: 9fccc6d8955f
Create Date: 2024-06-23 02:16:02.192532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99099f0055cf'
down_revision: Union[str, None] = '9fccc6d8955f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Actions_id'), 'Actions', ['id'], unique=True)
    op.create_index(op.f('ix_Actions_message'), 'Actions', ['message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Actions_message'), table_name='Actions')
    op.drop_index(op.f('ix_Actions_id'), table_name='Actions')
    op.drop_table('Actions')
    # ### end Alembic commands ###
